export const products = [
  {
    id: 1,
    name: "SK & SKL Series",
    image: "/skseries/Skseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 2,
    name: "SKP SERIES",
    image: "/skseries/Skpseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 3,
    name: "SKLW SERIES",
    image: "/skseries/Sklwseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 4,
    name: "SKWT SERIES",
    image: "/skseries/Skwtseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
];
