export const products = [
  {
    id: 1,
    name: "SK & SKL Series",
    image: "/skseries/Skseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 2,
    name: "SKP SERIES",
    image: "/skseries/Skpseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 3,
    name: "SKLW SERIES",
    image: "/skseries/Sklwseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 4,
    name: "SKWT SERIES",
    image: "/skseries/Skwtseries.png",
    route: "skpump",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 5,
    name: "SKMS SERIES",
    image: "/skseries/SKMSseries.png",
    route: "skpump",
    description: "CLOSED COUPLED, SMALL CENTRIFUGAL PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 6,
    name: "SK 168",
    image: "/skseries/ChemicalDosingPumpSK.png",
    route: "skpump",
    description: "Chemical Dosing Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 7,
    name: "SK 368 SERIES",
    image: "/skseries/ChemicalDiaphragmPumpSK368Series.png",
    route: "skpump",
    description: "Chemical Diaphragm Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 8,
    name: "SKVSP SERIES",
    image: "/skseries/VerticalSumpPumpSKVSPSeries.png",
    route: "skpump",
    description: "Vertical Sump Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 9,
    name: "PRE-CLEANER SYSTEM",
    image: "/skseries/PreCleanerSystem.png",
    route: "skpump",
    description: "SK PRE-CLEANER WITH AUTO DISCHARGE SYSTEM",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 10,
    name: "SKOSP SERIES",
    image: "/skseries/SKOSPSeries.png",
    route: "skpump",
    description: "OIL SKIMMER PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 11,
    name: "SK MIXER SERIES",
    image: "/skseries/SKMixerSeries.png",
    route: "skpump",
    description: "SK MIXER & AGITATOR",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
];
