export const products = [
  {
    id: 1,
    name: "SK & SKL Series",
    image: "/skseries/Skseries.png",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 2,
    name: "SKP SERIES",
    image: "/skseries/Skpseries.png",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 3,
    name: "SKLW SERIES",
    image: "/skseries/Sklwseries.png",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 4,
    name: "SKWT SERIES",
    image: "/skseries/Skwtseries.png",
    description: "Back Pull Out Solids & Slurries Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 5,
    name: "SKMS SERIES",
    image: "/skseries/SKMSseries.png",
    description: "CLOSED COUPLED, SMALL CENTRIFUGAL PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 6,
    name: "SK 168",
    image: "/skseries/ChemicalDosingPumpSK.png",
    description: "Chemical Dosing Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 7,
    name: "SK 368 SERIES",
    image: "/skseries/ChemicalDiaphragmPumpSK368Series.png",
    description: "Chemical Diaphragm Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 8,
    name: "SKVSP SERIES",
    image: "/skseries/VerticalSumpPumpSKVSPSeries.png",
    description: "Vertical Sump Pump",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 9,
    name: "PRE-CLEANER SYSTEM",
    image: "/skseries/PreCleanerSystem.png",
    description: "SK PRE-CLEANER WITH AUTO DISCHARGE SYSTEM",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 10,
    name: "SKOSP SERIES",
    image: "/skseries/SKOSPSeries.png",
    description: "OIL SKIMMER PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 11,
    name: "SK MIXER SERIES",
    image: "/skseries/SKMixerSeries.png",
    description: "SK MIXER & AGITATOR",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 12,
    name: "VC SERIES",
    image: "/skeroseries/VCSeries.png",
    description: "LIQUID RING VACUUM PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 13,
    name: "BF SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "MULTI STAGE BOILER FEED WATER PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 14,
    name: "OT SERIES",
    image: "/skeroseries/BFSeries.png",
    description: "SIDE CHANNEL OIL TRANSFER PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 15,
    name: "DT SERIES",
    image: "/skeroseries/DTSeries.png",
    description: "VOLUTE CASING DEAERATOR PUMP",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 16,
    name: "WOLTMAN FLOWMETER",
    image: "/setech/WoltmanFlowmeter.png",
    description: "COLD WATER HORIZONTAL WOLTMAN FLOWMETER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 17,
    name: "ELECTROMAGNETIC FLOWMETER",
    image: "/setech/ElectromagneticFlowmeter.png",
    description: "ELECTROMAGNETIC FLOWMETER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 18,
    name: "FLOWMETER CONTROLLER",
    image: "/setech/FlowmeterController.png",
    description: "FLOWMETER CONTROLLER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 19,
    name: "NUT CRACKER",
    image: "/setech/NutCracker.png",
    description: "NUT CRACKER",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 20,
    name: "GAS DETECTOR",
    image: "/setech/GasDetector.png",
    description: "GAS DETECTOR",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 21,
    name: "ULTRASONIC THICKNESS GAUG",
    image: "/setech/UltrasonicGauge.png",
    description: "ULTRASONIC THICKNESS GAUG",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 22,
    name: "CONVEYOR CHAIN",
    image: "/trp/PalmOilChain.png",
    description: "CONVEYOR CHAIN",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 23,
    name: "SPROCKETS",
    image: "/trp/Sprockets.png",
    description: "SPROCKETS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 24,
    name: "MC SERIES",
    image: "/seweurodrive/MCSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 25,
    name: "M SERIES",
    image: "/seweurodrive/MSeries.png",
    description: "KERNEL EXPELLER DRIVES & EFB PRESS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 26,
    name: "CN SERIES",
    image: "/seweurodrive/CNSeries.png",
    description: "DIGESTER DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 27,
    name: "R SERIES",
    image: "/seweurodrive/RSeries.png",
    description: "HELICAL GEAR MOTORS",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
  {
    id: 28,
    name: "M SERIES SCREW PRESS DRIVE",
    image: "/seweurodrive/MSeriesScrew.png",
    description: "SCREW PRESS DRIVE",
    features: [
      "Realiability",
      "Interchangeability",
      "Minimizing Inventory Requirements",
      "High Efficiency",
      "Longer Life Span",
    ],
    technical: [
      {
        flow: "Max 400m³/hr",
        head: "Max 100m",
        temp: "80°C ~ 120°C",
        sizes: "9 Pump Sizes",
        capacity: "Solid Size 50mm / 30% Solid Content",
      },
    ],
    applications: [
      "Refinery",
      "Palm Oil Mill",
      "Slurry Handling",
      "Corrosive & Abrasive Pulp",
      "Chemical Plant",
    ],
    model: [
      "SK 2.5 / 1.5",
      "SKL 2.5 / 1.5",
      "SK 3 / 2",
      "SKL 3 / 2",
      "SK 4 / 3",
    ],
  },
];
